name: CI & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    # Use Node 20 on Alpine for speed
    runs-on: ubuntu-latest
    container: node:20-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0  # fetch all history so we can push tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Bump patch version
        run: yarn version --patch

      - name: Push version bump & tags
        run: |
          git push origin HEAD:main
          git push origin --tags

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
