name: CI & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # no container: … block here

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn version --patch

      - name: Push version bump & tags
        run: |
          git push origin HEAD:main
          git push origin --tags

      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
